const items =[
    {
        id: '001',
        image: 'item-images/image-1.jpg',
        company_name : 'Nike',
        product_name: 'Solid blue cotten tshirt',
        category: 'MensWear',
        original_price: 500,
        current_price: 250,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',

    },
    {
        id: '002',
        image: 'item-images/image-2.jpg',
        company_name : 'Puma',
        product_name: 'Casual Wear Blue Sneakers',
        category: 'MensWear',
        original_price: 5000,
        current_price: 2500,
        discount_percentage: 50,
        return_period: 10,
        delivery_date: '10 Dec 2023',   
    },
    {
        id: '003',
        image: 'item-images/image-3.jpg',
        company_name : 'Boat',
        product_name: 'Boat Headphone 4',
        category: 'Electronics',
        original_price: 700,
        current_price: 450,
        discount_percentage: 30,
        return_period: 15,
        delivery_date: '10 Dec 2023', 
    },
    {
        id: '004',
        image: 'item-images/image-4.jpg',
        company_name : 'Iphone',
        product_name: 'IPhone 14 Pro Max',
        original_price: 150000,
        category: 'Electronics',
        current_price: 7000,
        discount_percentage: 30,
        return_period: 15,
        delivery_date: '10 Dec 2023', 
    },
    {
        id: '005',
        image: 'item-images/image-5.jpg',
        company_name : 'Zara',
        product_name: 'Winter Wear',
        category: 'WomensWear',
        original_price: 5200,
        current_price: 1500,
        discount_percentage: 45,
        return_period: 7,
        delivery_date: '10 Dec 2023', 
    }
]